/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as BrilinkIndexRouteImport } from './routes/brilink/index'
import { Route as SalesTodayRouteImport } from './routes/sales/today'
import { Route as ReportsDateRouteImport } from './routes/reports/$date'
import { Route as BrilinkHistoryRouteImport } from './routes/brilink/history'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const BrilinkIndexRoute = BrilinkIndexRouteImport.update({
  id: '/brilink/',
  path: '/brilink/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTodayRoute = SalesTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => SalesRoute,
} as any)
const ReportsDateRoute = ReportsDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ReportsRoute,
} as any)
const BrilinkHistoryRoute = BrilinkHistoryRouteImport.update({
  id: '/brilink/history',
  path: '/brilink/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/categories': typeof CategoriesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roles': typeof RolesRoute
  '/sales': typeof SalesRouteWithChildren
  '/users': typeof UsersRoute
  '/brilink/history': typeof BrilinkHistoryRoute
  '/reports/$date': typeof ReportsDateRoute
  '/sales/today': typeof SalesTodayRoute
  '/brilink': typeof BrilinkIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/categories': typeof CategoriesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/users': typeof UsersRoute
  '/brilink/history': typeof BrilinkHistoryRoute
  '/reports/$date': typeof ReportsDateRoute
  '/sales/today': typeof SalesTodayRoute
  '/brilink': typeof BrilinkIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sales': typeof SalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-logs': typeof AuditLogsRoute
  '/categories': typeof CategoriesRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRouteWithChildren
  '/roles': typeof RolesRoute
  '/sales': typeof SalesRouteWithChildren
  '/users': typeof UsersRoute
  '/brilink/history': typeof BrilinkHistoryRoute
  '/reports/$date': typeof ReportsDateRoute
  '/sales/today': typeof SalesTodayRoute
  '/brilink/': typeof BrilinkIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sales/': typeof SalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-logs'
    | '/categories'
    | '/products'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/users'
    | '/brilink/history'
    | '/reports/$date'
    | '/sales/today'
    | '/brilink'
    | '/reports/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-logs'
    | '/categories'
    | '/products'
    | '/profile'
    | '/roles'
    | '/users'
    | '/brilink/history'
    | '/reports/$date'
    | '/sales/today'
    | '/brilink'
    | '/reports'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/audit-logs'
    | '/categories'
    | '/products'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/users'
    | '/brilink/history'
    | '/reports/$date'
    | '/sales/today'
    | '/brilink/'
    | '/reports/'
    | '/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogsRoute: typeof AuditLogsRoute
  CategoriesRoute: typeof CategoriesRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RolesRoute: typeof RolesRoute
  SalesRoute: typeof SalesRouteWithChildren
  UsersRoute: typeof UsersRoute
  BrilinkHistoryRoute: typeof BrilinkHistoryRoute
  BrilinkIndexRoute: typeof BrilinkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/brilink/': {
      id: '/brilink/'
      path: '/brilink'
      fullPath: '/brilink'
      preLoaderRoute: typeof BrilinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/today': {
      id: '/sales/today'
      path: '/today'
      fullPath: '/sales/today'
      preLoaderRoute: typeof SalesTodayRouteImport
      parentRoute: typeof SalesRoute
    }
    '/reports/$date': {
      id: '/reports/$date'
      path: '/$date'
      fullPath: '/reports/$date'
      preLoaderRoute: typeof ReportsDateRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/brilink/history': {
      id: '/brilink/history'
      path: '/brilink/history'
      fullPath: '/brilink/history'
      preLoaderRoute: typeof BrilinkHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsDateRoute: typeof ReportsDateRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsDateRoute: ReportsDateRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface SalesRouteChildren {
  SalesTodayRoute: typeof SalesTodayRoute
  SalesIndexRoute: typeof SalesIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesTodayRoute: SalesTodayRoute,
  SalesIndexRoute: SalesIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogsRoute: AuditLogsRoute,
  CategoriesRoute: CategoriesRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RolesRoute: RolesRoute,
  SalesRoute: SalesRouteWithChildren,
  UsersRoute: UsersRoute,
  BrilinkHistoryRoute: BrilinkHistoryRoute,
  BrilinkIndexRoute: BrilinkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
